#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MOBILE_DIR="$ROOT_DIR/packages/mobile"
ENV_LOCAL_FILE="$MOBILE_DIR/.env.local"

cleanup() {
  rm -f "$ENV_LOCAL_FILE"
}
trap cleanup EXIT INT TERM

normalize_public_api_url() {
  local url="${1//[[:space:]]/}"
  url="${url%/}"

  if [[ "$url" =~ \.ngrok-free$ ]]; then
    url="${url}.app"
    echo "Fixed incomplete ngrok URL to: ${url}" >&2
  fi

  printf '%s' "$url"
}

if [[ -z "${AIRPOOL_PUBLIC_API_URL:-}" ]]; then
  echo "Missing AIRPOOL_PUBLIC_API_URL."
  echo ""
  echo "Remote testers need a public backend URL (Expo tunnel only shares the app bundle)."
  echo ""
  echo "Quick setup:"
  echo "  1. Start backend: make dev-backend"
  echo "  2. Expose port 5000: make tunnel-backend"
  echo "  3. From project root:"
  echo "       AIRPOOL_PUBLIC_API_URL=https://YOUR-PUBLIC-URL make dev-remote"
  echo "     Or from packages/mobile:"
  echo "       AIRPOOL_PUBLIC_API_URL=https://YOUR-PUBLIC-URL yarn dev:remote"
  exit 1
fi

PUBLIC_API_URL="$(normalize_public_api_url "$AIRPOOL_PUBLIC_API_URL")"

if [[ ! "$PUBLIC_API_URL" =~ ^https?:// ]]; then
  echo "AIRPOOL_PUBLIC_API_URL must start with http:// or https://"
  echo "Got: $PUBLIC_API_URL"
  echo ""
  echo "Use the full URL from ngrok/cloudflared, e.g.:"
  echo "  https://abc123.ngrok-free.app"
  exit 1
fi

if [[ "$PUBLIC_API_URL" =~ \.ngrok-free(/|$) && ! "$PUBLIC_API_URL" =~ \.ngrok-free\.app(/|$) ]]; then
  echo "Ngrok URL looks incomplete. Use the full URL ending in .ngrok-free.app"
  echo "Got: $PUBLIC_API_URL"
  exit 1
fi

export EXPO_PUBLIC_API_BASE_URL="${PUBLIC_API_URL}/api/v1"
export EXPO_PUBLIC_SOCKET_URL="${PUBLIC_API_URL}"

cat > "$ENV_LOCAL_FILE" <<EOF
# Auto-generated by scripts/start-remote-mobile.sh — removed when Expo stops
EXPO_PUBLIC_API_BASE_URL=${EXPO_PUBLIC_API_BASE_URL}
EXPO_PUBLIC_SOCKET_URL=${EXPO_PUBLIC_SOCKET_URL}
EOF

echo "Remote mobile dev server"
echo "  API:    ${EXPO_PUBLIC_API_BASE_URL}"
echo "  Socket: ${EXPO_PUBLIC_SOCKET_URL}"
echo ""
echo "Share the Expo QR code with anyone — same Wi-Fi is not required."
echo "Press Ctrl+C to stop (this also clears .env.local)."
echo ""

cd "$MOBILE_DIR"
exec yarn start:tunnel
